version: '3.3'
#jinja2: lstrip_blocks: “True”

services:

    front:
        image: ommzzz/projects:movie-swiper-front-23cff71a368afbc470e31f9dbfbeea2a0d327c05

        container_name: MS-front

        restart: always

        ports:
          - "80:3000"

        environment:
          REACT_APP_API_URL: http://ugol.space
          REACT_APP_FRONT_URL: http://ugol.space


    back:
        image: ommzzz/projects:movie-swiper-back-23cff71a368afbc470e31f9dbfbeea2a0d327c05
        container_name: MS-back

        restart: always

        ports:
          - "5000:80"

        environment:
          ## Flask configs
          FLASK_APP: app.py
          FLASK_ENV: 'development'

          ## Useful variables
          SERVER_NAME: ugol.space
          FRONT_NAME: ugol.space

        command: ['python3', '/app/app.py']

    redis:
        image: bitnami/redis:latest

        container_name: MS-redis

        restart: always

        ports:
          - "9736:6379"

        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb

        environment:
          ALLOW_EMPTY_PASSWORD: 'yes' 
