- name: Stop and remove existing stage-postgres container
  docker_container:
    name: stage-postgres
    state: absent

- name: Get list of files from backup server
  delegate_to: ugol
  find:
    paths: '{{ remote_backup_directory }}'
  register: found_files

- name: Get latest file
  delegate_to: ugol
  set_fact:
    latest_file: '{{ found_files.files | sort(attribute="mtime",reverse=true) | first }}'
    
- debug:
    var: latest_file

- name: Copy latest postgres backup on server
  delegate_to: ugol
  shell: 'scp -i ~/.ssh/ansible_ugol -o "StrictHostKeyChecking no" {{ latest_file.path }} dms@poligon01.ugol.space:/home/{{ ansible_user }}/postgres_dump.sql'

# - name: Copy latest postgres backup on server
#   delegate_to: ugol
#   synchronize:
#     src: '{{ latest_file.path }}'
#     dest: '/home/{{ ansible_user }}/postgres_dump.sql'
    
